### ISSUE TITLE
Mixed subscriptions creation and editing from the admin panel support

### ISSUE THREAD

**Issue by artemverbo** [kathyisawesome/wc-mnm-satt-bridge#5]
Hi Kathy! Thank you for the amazing plugin and this bridge to support mixed subscriptions, super useful.

A question I have is, do you have a plan to add support of mixed subscriptions creation/editing from the admin panel? At the moment going into Subscriptions and clicking "Edit" on the mix does nothing, however, doing the same in the normal (non-subscription) mixed Orders, would allow, say to create mixes via a modal popup.

A use case we have is we are building a subscription-based "wine club" for a client and in addition to normal online registration / subscription done by users, they would like store operators to be able to do so at the cellar door, when customers visit then physically.

Not sure (yet) about the level of complexity of such an addition, as the website-facing functionality is more or less covered by the two plugins and this bridge 👍

**Comment by helgatheviking** [comment]
Hi @artemverbo Glad you dig this bridge plugin! A Mix and Match wine club is perfect use case and eventually, I need to get it rolled into MNM itself. 

Is this what you are describing?
![Screen Recording 2020-09-28 at 04 55 32 75 PM](https://user-images.githubusercontent.com/507025/94494799-4dbaf480-01ad-11eb-8950-8fec4149aa7a.gif)

Totally makes sense that this would be needed for subscriptions too... and luckily it appears to be only a question of getting the existing scripts to load on the Subs page, I can probably get that into the next minor release for Mix and Match.

One question though... I just noticed there's no order note to record that the quantities are changed from the original subscription? Looks like the same thing applies to orders too. Is that something you think would be needed?

**Comment by artemverbo** [comment]
@helgatheviking thank you for the prompt reply! Yep that's exactly what I was after, and sounds perfect that this is not something too complex to add. I believe then this also should work for the process of manually/admin **created** mixed subscriptions (eg not just editing of the existing subscriptions).

And I think the quantities changed note is not critical for my particular use case at this stage.

**Comment by helgatheviking** [comment]
1.10.3 went out just now so should be available soon. It should include the editing in subscriptions feature.
