### ISSUE TITLE
Switch between mix contents AND subscription plans

### ISSUE THREAD

**Issue by artemverbo** [kathyisawesome/wc-mnm-satt-bridge#9]
Hi Kathy! I know you already hate me with all the support requests, one more (not urgent) please, more of a feature request.

I can see that you have the following in the code
```
// Disallow plan switching for container. Only content switching permitted!
```

Is there a specific reason/complication to now allow switching between plans if that's ticked as well as contents? Would be great if that'd be possible, but not sure how hard is that.

Thank you!
Artem.

**Comment by helgatheviking** [comment]
Hi Artem! Yes, you are definitely keeping me busy this week! :)

So you would like to have the ability to switch between subscription schemes? For example... switch the Mix and Match product from 1/month to 1/quarter? Let me ask the All Products for Subscriptions team to see why we are doing it this way.

**Comment by artemverbo** [comment]
Yep, in other not-MnM "simple" products with multiple subscription plans, if "Allow switching" "Between Subscription Plans" is enabled, a customer is able to edit their subscription and select another plan, but if I edit MnM product in a same way (and I also have "Allow switching" "Between Mix and Match Configurations" ticked, I can change the configuration, but the subscriptions plan selector is not visible and I've found the above comment in the bridge code, disabling that, assuming there is some limitation somewhere :)

**Comment by helgatheviking** [comment]
Hi Artem, so I spoke with the SomewhereWarm team behind All Products for WooCommerce Subscriptions, and the reason they don't allow scheme switching on bundle type products is that there's no way to prevent Subscriptions from breaking it apart into different subscriptions... ie, breaking the parent/child relationships and putting each item in a different, new subscription.

If they've already run into this wall and not found a way around it, then unfortunately, I don't have the woman-power to take a new look right now.

**Comment by artemverbo** [comment]
No problems, I understand there are limitations here and there in a complex system. Thank you for checking that with their team Kathy!

**Comment by helgatheviking** [comment]
The Subscriptions plugin is exceptionally complex! And that appears to be the bottle neck for the moment.
